### PR TITLE
Helper method for mode dependant constant correction

### PR DESCRIPTION
**Pull request by DominicOram**
Presumably required for https://github.com/ISISComputingGroup/IBEX/issues/5800. @ThomasLohnert?

### CODE REVIEW

**Comment by ThomasLohnert** [comment]
Ah. Yes indeed

**Review by DominicOram — COMMENTED** [review]
Minor changes here and more comments on ticket itself

**Comment by DominicOram** [comment]
@ThomasLohnert are you able to have a look at this or shall I? I suspect you didn't get notified about the review as I made the PR?

**Comment by ThomasLohnert** [comment]
Updated

**Comment by ThomasLohnert** [comment]
Updated @DominicOram

**Review by ThomasLohnert — APPROVED** [review]

**Pull request merged**
